CREATE TABLE color
(
    color_id    BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    color_code  VARCHAR(255),
    color_label VARCHAR(255),
    color_hex   VARCHAR(255),
    CONSTRAINT pk_color PRIMARY KEY (color_id)
);

CREATE TABLE lifecycle_status
(
    lifecycle_status_id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    status_code         VARCHAR(255),
    description         VARCHAR(255),
    CONSTRAINT pk_lifecycle_status PRIMARY KEY (lifecycle_status_id)
);

CREATE TABLE product
(
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name              VARCHAR(255),
    slug              VARCHAR(255),
    blurb             VARCHAR(255),
    color_id          BIGINT,
    image_url         VARCHAR(255),
    usefulness_rating DOUBLE PRECISION                        NOT NULL,
    qty               INTEGER                                 NOT NULL,
    lifecycle_status  BIGINT,
    created_at        TIMESTAMP WITHOUT TIME ZONE,
    updated_at        TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_product PRIMARY KEY (id)
);

CREATE TABLE user_roles
(
    user_id BIGINT NOT NULL,
    role    VARCHAR(255)
);

CREATE TABLE users
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    username   VARCHAR(255)                            NOT NULL,
    password   VARCHAR(255)                            NOT NULL,
    email      VARCHAR(255)                            NOT NULL,
    enabled    BOOLEAN                                 NOT NULL,
    created_at TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_users PRIMARY KEY (id)
);

ALTER TABLE users
    ADD CONSTRAINT uc_users_username UNIQUE (username);

ALTER TABLE product
    ADD CONSTRAINT FK_PRODUCT_ON_COLOR FOREIGN KEY (color_id) REFERENCES color (color_id);

ALTER TABLE product
    ADD CONSTRAINT FK_PRODUCT_ON_LIFECYCLE_STATUS FOREIGN KEY (lifecycle_status) REFERENCES lifecycle_status (lifecycle_status_id);

ALTER TABLE user_roles
    ADD CONSTRAINT fk_user_roles_on_user FOREIGN KEY (user_id) REFERENCES users (id);