CREATE TABLE colors
(
    color_id    BIGINT NOT NULL,
    color_code  VARCHAR(255),
    color_label VARCHAR(255),
    color_hex   VARCHAR(255),
    CONSTRAINT pk_colors PRIMARY KEY (color_id)
);

CREATE TABLE widget
(
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name              VARCHAR(255),
    slug              VARCHAR(255),
    blurb             VARCHAR(255),
    color_id          BIGINT,
    image_url         VARCHAR(255),
    usefulness_rating DOUBLE PRECISION                        NOT NULL,
    qty               INTEGER                                 NOT NULL,
    lifecycle_status  VARCHAR(255),
    created_at        TIMESTAMP WITHOUT TIME ZONE,
    updated_at        TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_widget PRIMARY KEY (id)
);

ALTER TABLE widget
    ADD CONSTRAINT FK_WIDGET_ON_COLOR FOREIGN KEY (color_id) REFERENCES colors (color_id);