-- Step 1: Create new roles table
CREATE TABLE roles (
                       role_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                       role_name VARCHAR(255) UNIQUE NOT NULL
);

-- Step 2: Insert distinct roles from user_roles
INSERT INTO roles (role_name)
SELECT DISTINCT role FROM user_roles WHERE role IS NOT NULL;

-- Step 3: Add new role_id column to users
ALTER TABLE users ADD COLUMN role_id BIGINT;

-- Step 4: Update each user's role_id using a correlated subquery
UPDATE users
SET role_id = (
    SELECT r.role_id
    FROM roles r
             JOIN user_roles ur ON ur.role = r.role_name
    WHERE ur.user_id = users.id
)
WHERE EXISTS (
    SELECT 1
    FROM user_roles ur
    WHERE ur.user_id = users.id
);

-- Step 5: Add foreign key constraint
ALTER TABLE users
    ADD CONSTRAINT fk_users_role FOREIGN KEY (role_id) REFERENCES roles(role_id);

-- Step 6: Drop old join table
DROP TABLE user_roles;
